
apiVersion: v2
name: openebs
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 3.10.0

dependencies:
  - name: openebs
    repository: https://openebs.github.io/charts
    version: 3.10.0